name: CI/CD for Extractors

on:
  push:
    branches:
      - main

jobs:
  determine-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      RUNNER_CHANGED_FILES: "d "
      

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
            fetch-depth: 0 # Fetch full history

      - name: Get List of Changed Files
        id: changed-files
        run: |
          echo changed files: $RUNNER_CHANGED_FILES
          export RUNNER_CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          export RUNNER_CHANGED_FILES=$(python3 -c "import os;files=os.getenv('RUNNER_CHANGED_FILES');files=files.split('\n');exec('''for f in files:print(os.path.join(*[x for x in f.split('/')[:2]]))''')")
          echo changed files: $RUNNER_CHANGED_FILES

      - name: Generate Matrix
        id: set-matrix
        run: |
          declare -a EXTRACTORS=()
          echo changed files: $RUNNER_CHANGED_FILES
          for FILE in $RUNNER_CHANGED_FILES; do
            case $FILE in
              pastas/projeto_1)
                EXTRACTORS+=("{\"name\":\"projeto_1\",\"directory\":\"pastas/projeto_1\",\"environment\":\"prod\"}");;
              pastas/projeto_2)
                EXTRACTORS+=("{\"name\":\"projeto_2\",\"directory\":\"pastas/projeto_2\",\"environment\":\"dev\"}");;
              pastas/projeto_3)
                EXTRACTORS+=("{\"name\":\"projeto_3\",\"directory\":\"pastas/projeto_3\",\"environment\":\"dev\"}");;
            esac
          done
          echo "matrix=[${EXTRACTORS[@]}]"
          echo "matrix=[${EXTRACTORS[@]}]" >> $GITHUB_ENV
          echo "::set-output name=matrix::${matrix}"

  deploy:
    needs: determine-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extractor: ${{ fromJson(needs.determine-changes.outputs.matrix) }}

    environment: ${{ matrix.extractor.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Build and Deploy
        run: |
          echo ${{ matrix.extractor.directory }} && bash build.sh
