name: CI/CD for Extractors

on:
  push:
    branches:
      - main

jobs:
  determine-changes:
    runs-on: ubuntu-latest
    environment: 
      name: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
            fetch-depth: 0 # Fetch full history

      - name: Print
        run: |
          echo ${{ vars.VARIAVEL }}
          echo ${{ secrets.VARIAVEL }}
